### ISSUE TITLE
Open Database via URL

### ISSUE THREAD

**Issue by sandreas** [mstarke/MacPass#441] opened 2016-03-25 15:04 UTC
I would like to open a Database from an URL (not Filesystem), like http://mydomain.com/keepassdb.db. It would be cool if it could support Basic Auth and WebDAV for saving back changes.

**Comment by christopherowen** [comment] 2016-04-08 20:00
#99

**Comment by lenucksi** [comment] 2016-04-29 08:54
👍

**Comment by mstarke** [comment] 2016-08-17 08:27
Duplicate of #99

**Closed by mstarke** 2016-08-17 08:27 UTC
Labels: Duplicate
