### ISSUE TITLE
Autotype does not work with Safari in fullscreen mode

### ISSUE THREAD

**Issue by mmdl** [mstarke/MacPass#592] opened 2017-06-01 17:29 UTC
Autotype does not work with Safari in fullscreen mode. I change window by pressing `⌘TAB`.

**Comment by mstarke** [comment] 2017-06-02 08:45
Duplicate of #466. Fixed in 109f9c879913edb822a1f98dcf1aae277e45f1e5. Will be deliverd with 0.7 or with a nightly/contiuous build. Sorry for the long dealy!

**Closed by mstarke** 2017-06-02 08:45 UTC
Labels: Duplicate
