### ISSUE TITLE
Crash on closing file preview

### ISSUE THREAD

**Issue by sMau** [mstarke/MacPass#589] opened 2017-05-17 07:24 UTC
On closing the preview of an attached file MacPass crashes.
Steps to reproduce:
1. Open file preview with the "preview" button
2. Close file preview with the "X" button

Steps need to be done can be seen in the attached screenshots. If further information could be helpful, of course, I will provide them gladly.

MacPass version: 0.6.2 (12420)
on MacOS 10.12.3, 10.12.4 and 10.12.5
Full crash output from MacOS:
https://pastebin.com/9aWG8G8s

![preview](https://cloud.githubusercontent.com/assets/1273296/26142778/650ecade-3ae2-11e7-8182-33a075c2b34f.png)
![close](https://cloud.githubusercontent.com/assets/1273296/26142783/66d22140-3ae2-11e7-8c8e-172fefa186f4.png)

**Comment by mstarke** [comment] 2017-05-17 07:29
Duplicate of #588

**Closed** 2017-05-17 07:29 UTC
