### ISSUE TITLE
[Feature Request] Allow for addition of custom icons

### ISSUE THREAD

**Issue by eboddington** [mstarke/MacPass#314] opened 2015-02-12 16:15 UTC
KeePass 2 for Windows allows me to add custom icons for entries. These are displayed fine in MacPass but I can only change to the built-in set of icons, and can't add new ones.

**Comment by Couto** [comment] 2015-02-15 17:55
This might sound like a small feature, but it's really helpful to visually identify the correct folder/password from the list. It's actually one of the features that I miss the most.

**Comment by ellisbodds** [comment] 2015-02-16 12:04
Yeah, me too. Given the current development state of MP, it doesn't seem like a glaring omission, but it'd be really nice to have.

**Comment by mstarke** [comment] 2015-02-16 17:56
I'm all in favour since it's a rather simple task. The UI needs to be good for adding/removing the icons but the rest ist a no brainer. Since @JoannaOlsen has contributed all the icons I will try to add the feature with the updated icons.

Another note: Keepass allows for custom data and since the icons are all 16x16 i was pondering with the Idea of adding full sizes (with a reasonable maximum size) icons as well and load them. This way MacPass can display the full sized versions instead of those ugly small ones. Problem with this is though that if someone edits the icons outside of MacPass I have to manually remove the special MacPass version since it might not be valid anymore. But for first-class MacPass users this might be of some benefit.

**Comment by NicolasSiver** [comment] 2015-02-27 08:43
Also Keepass original supports nice plugin, - Favicon Downloader, most useful plugin that I have used for years.

**Comment by mstarke** [comment] 2015-02-27 09:44
There's an issue related to this request: #132

**Comment by alakani** [comment] 2016-03-06 16:56
I would really, really like this feature too.  I don't mind if it doesn't even have a UI, maybe it can allow dropping a new icon over the one in Inspector, like Finder supports.  No high res icons needed either, 16x16 is fine.

**Comment by zmcode** [comment] 2016-03-07 13:07
+1 for this request and actually I am in the same situation as @alakani: MacPass version 0.6.2 does not display custom icons added from KeePass 2.

**Comment by mstarke** [comment] 2016-03-08 18:09
The missing display of custom icons is a regression in 0.6

**Comment by tpluscode** [comment] 2017-08-31 11:06
@zmcode not only it doesn't display custom icons, it also cleared custom icons I had set for folders (entry icons seem to have been kept intact)

**Comment by mstarke** [comment] 2017-08-31 11:08
This behaviour is fixed in the continuous release;

**Comment by henriqueccruz** [comment] 2017-09-16 01:23
Downloaded continuous and am a bit clueless about how to do it.
Do I need some plugin to achieve this?

**Comment by mstarke** [comment] 2017-09-16 07:25
It's not pushed yet since there are some minor issues that I need to iron out.

**Comment by mstarke** [comment] 2017-09-16 15:02
My current approach for this feature:

1. dragging an icon in the inspector icon will use it as a custom icon
1. dragging an icon onto the icon selection popup will add it as a custom icon
1. the download button in the icon selection popup will download the websites favicon as a new custom icon.
1. dragging a custom icon out of the icon selection popup will delete that icon from the database 
1. custom icons in the icon selection popup have a context menu with one entry "delete"
1. pressing ```alt``` while the icon selection popup is open will show remove buttons on all custom icons and a click on those will delete the icon

I've already implemented 2. and 3. and now are onto 1. 4. 5. and 6.

**Comment by mstarke** [comment] 2017-09-20 19:47
1. and 5. are working as well so basic functionality for adding, setting and deleting custom icons works.  That leaves 4. and 6.

**Comment by mstarke** [comment] 2017-11-27 06:27
I've decided to leave out 4 and 6 for now since the functionality is there. Further improvements should be documented in a different issue.

**Closed by mstarke** 2017-11-27 06:27 UTC
Labels: Enhancement, Keepass Feature

**Comment by kud** [comment] 2020-06-09 08:59
Hey @mstarke . I would like to understand where is the progress of this feat, because I don't understand how to define an icon for a folder. Thanks!

**Comment by kud** [comment] 2020-06-09 09:11
Oh okay, I think I got it. I had a bug that selecting the group also selecting the first entry and I never saw the folder edition in inspector, it always opened the entry edition.

**Comment by mstarke** [comment] 2020-06-09 09:13
This "bug" is a problem of the auto-seleciton of the last selected entry in a group. This leads to the cumbersome way of re-clicking on the group to get the group selection to show up. This needs a lot of rework which I've been pushing out to the point where I can refactor the UI to remove any old cruft and raise the deployment target to 10.13 or higher.

**Comment by kud** [comment] 2020-06-09 09:23
Yes, that's it!

Thank you @mstarke !
