### ISSUE TITLE
Safari plugin

### ISSUE THREAD

**Issue by Sosoyan** [mstarke/MacPass#509] opened 2016-11-01 21:01 UTC
Is there anyway to get safari integration?

**Comment by mstarke** [comment] 2016-11-06 11:58
There is a port of Passifox for Safari but I have no information on the current state of this port. You can use MacPassHTTP to get it to work. Another way is to use global autotype since it's the method that should work with any application without special plugins.

**Comment by mlazowik** [comment] 2017-02-27 20:35
Duplicate of #77?

**Comment by mstarke** [comment] 2017-02-28 08:05
It is…

**Closed by mstarke** 2017-02-28 08:05 UTC
Labels: Duplicate
