### ISSUE TITLE
Additions to the notes field are not being saved. 

### ISSUE THREAD

**Issue by chmedly** [mstarke/MacPass#544] opened 2017-01-26 17:05 UTC
I've only noticed this since upgrading to Sierra but I don't know if the upgrade is the culprit.  But, what is happening is that if I add additional text to the notes and save it doesn't actually save.  When I reopen MacPass the notes field contains only the old text.  I'm running Version 0.6.2 (12420).

**Comment by mstarke** [comment] 2017-01-26 17:15
Duplicate of #445 #455 #463 #485

**Closed by mstarke** 2017-01-26 17:15 UTC
Labels: Duplicate
