### ISSUE TITLE
Global Autotype working?

### ISSUE THREAD

**Issue by yarongol** [mstarke/MacPass#279] opened 2014-12-08 13:08 UTC
As far as I understand, with global autotype, I am supposed to browse (Chrome) to a URL, press Ctrl-Alt-M and autotype will work. This at least is how I work in Keepass for Windows. 
It does not work for me (MacPass 0.5.1, Yosemite 10.10.1). Enable global-autotype is on and the shortcut is there (though on a separate note -- it cannot be replaced right now)
I have some (rusting) dev capabilities and xcode installed if you want me to debug something.

**Comment by sickill** [comment] 2015-04-10 21:28
+1 for supporting "Auto-Type-Window".

Also, it would be great if user got some visual feedback about "no matching entry found" when hitting global hotkey. Something like the popup/tooltip that displays "Username copied!" would be awesome here.

**Comment by boeren** [comment] 2015-05-03 22:28
For my system (OSX 10.10.3) there is still a problem in the current master concerning autotype. The last 0.5.1 alpha (2556) works like a charm, but the last master releases always lower-case the first letter of the password thus leading into a faulty password... Passwords with a lower-case letter in the beginning actually work.

**Comment by mstarke** [comment] 2015-05-04 09:14
The auto type code had a lot of bugs and misbehaviours fixed, so this might be a result of them. My tests work, guess I should add one that tests for lower/upper case in passwords :)

**Comment by DarwinAwardWinner** [comment] 2015-06-18 01:57
One issue I've run into using autotype is that sometimes I also have a password saved in my browser, and it will also autofill the password on the `{TAB}` that switches from the username field to the password field, and the password will be typed twice and the login will fail. In order to get around this, I need to use an autotype sequence of`{CLEARFIELD}{USERNAME}{TAB}{DELAY 20}{CLEARFIELD}{PASSWORD}{ENTER}`. (The delay is to give the browser tome to complete its autofill. It's probably a race condition, and I have no idea of what the appropriate delay is.) Is there any way I can make this default for all entries instead of manually editing each one? (Alternately, can something like this become the builtin default autotype? Those CLEARFIELDs make it a lot more robust, in case you started typing the username before remembering to use autotype.

**Comment by mstarke** [comment] 2015-06-18 07:49
I plan to add the setting to specify the default auto type sequence. Until then you can edit the sequence in the root group. The default behaviour is to inherit the sequence an thus all new entries and groups will get the one from the root group.

I will however not change the default to comply with the Keepass' defaults.

**Comment by DarwinAwardWinner** [comment] 2015-06-18 08:32
Changing the autotype sequence on the root group is perfect. Thanks.

**Comment by jpduckwo** [comment] 2015-07-02 12:44
Hey, I'm a bit confused if the Ctrl-V autotype style functionality is working or not? I can't seem to get it working if it is...

Awesome work by the way, looks nicer than the original ;)

**Comment by akcasoy** [comment] 2016-11-08 10:11
Could please someone check if autotype still works in 10.12 (Sierra)?
I somehow could not manage to see it working.

**Comment by sickill** [comment] 2016-11-08 10:14
I used global autotype today on Sierra and it worked fine.

**Comment by akcasoy** [comment] 2016-11-08 10:19
I think this feature lacks a clear "how to". I spend the last 1 hour to understand how it should work.. 
Does a KeePass Entry URL have to match the current URL in browser? Or how does it match the entry?

I also enabled the preview, but do not see any preview on the screen whether it has found the entry or not. 
shortcut is ctrl+alt+m right?

**Comment by mstarke** [comment] 2016-11-08 11:39
I tend to forget that MacPass is used by users not knowing KeePass for windows and the features. This yields the missing documentation for a lot of features of MacPass.

I starte a wiki page for [Autotype](https://github.com/mstarke/MacPass/wiki/Autotype) to explain the concept and will try to fill in the blanks ASAP.

**Comment by akcasoy** [comment] 2016-11-08 11:43
Thank you very much Michael. I actually found out and read a bit of the KeePass Autotype Documentation. I somehow still miss another small point..

**Comment by michaelblyons** [comment] 2016-11-09 19:20
### Autotype
Thanks for the Autotype wiki page. It will be super helpful for people who are new to KeePass.

As one of those people, I have a question about it: I don't quite understand at the end of [the last section][1] why Entry A is used. Based on the explanation, I would expect Entry B to be used. I could be misunderstanding, though.

There are a couple of typos in the wiki as well. If you want, I can also proofread the page.

### Control sequences
Can you make a wiki page with a table of all the control sequences and what they do? (e.g. `{TAB}`, `{ENTER}`, etc.) Is there, for instance, a `{WAIT:10}` control or other features I just wouldn't know about? I can open a new issue if you'd prefer.

[1]: https://github.com/mstarke/MacPass/wiki/Autotype#example-in-safari-1

**Comment by mstarke** [comment] 2016-11-09 20:39
@akcasoy I have encountered some cases where the hotkey is not triggered correctly. Sometimes enabling and disabling global autotype fixes that. I should investigate this further. MacPass of course must run but the database can be locked. If you invoke autotype and all databases are locked, MacPass will print you to unlock at least one. If you do not unlock the database containing the required entry and another one is unlocked, autotype will fail as it's not asking for all databases to be unlocked. MacPass always reports feedback when autotype was invoked even if no match was found to be able to see if the keystroke worked. You do not need to add the hot key to the system preferences.

**Comment by mstarke** [comment] 2016-11-09 20:45
@michaelblyons you are right, the match is B. The last sentence was wrong. For the available keys you can take a look at the KeePass website. Not all are supported but quite a few. The command to wait is ```{DELAY <seconds>}``` and MacPass should support it if I did not break it ;-).

**Comment by oehm-smith** [comment] 2016-11-10 00:37
Wouldn't it be better to match on URL first since it is more likely to 
be more accurate as Titles can be fairly 'loose' and ill-defined?

With the 'which database has the password', how about Macpass asks which 
databases from the recently used list?

**Comment by mstarke** [comment] 2016-11-10 11:23
@oehm-smith might be but I try to stay compatible with KeePass and KeePass matches in the that order.

**Comment by oehm-smith** [comment] 2016-11-10 21:50
That makes sense.

**Comment by LightServant** [comment] 2017-03-02 10:29
Global Autotype does again not work for me. 

Wenn I evoke the keyboard-shortcut nothing happens. Window Titles, and URL match at least 1 pattern in my Database.
The Mac Console raises an entry with the message "An uncaught exception was raised" as well as two more entries with messages "<private>".  Not very enlighting, but I can't seem to find anything more in the log-files. 
I'm currently working with the binary version 0.6.2 (12420).

Thanks in advance!

**Comment by mstarke** [comment] 2017-03-02 10:34
There where numerous bugs with autotype and those should be fixed in the current master. Those fixes will be available in 0.7 as well.

**Comment by LightServant** [comment] 2017-03-02 10:37
Thanks for the quick response! So are you suggesting I should built from source or is 0.7 to be released soon anyway?

**Comment by cmcginty** [comment] 2017-04-13 04:32
Is .7 going to be released? It's still clear how to get auto-type working. What does "Title" even match? Can someone post an example that works for them? Will autotype work in iTerm2 or just a browser?

**Comment by mstarke** [comment] 2017-04-16 08:07
0.7 is coming eventually. I will release 0.6.3 within the week to fix major bugs but without a complete 0.7 feature set. 

Autotype works for any app ( via context menu or shortcut when MacPass is the front most app) as well as global Autotype (hotkey based autotype when MacPass is in the background) since it relies only on the window title of an app.

**Comment by LightServant** [comment] 2017-04-16 08:41
I've worked with a compiled pull from GitHub which i suppose is 0.7 and on my macOS Sierra with Safari Global Autotype return the wrong Window Title. I think it returns the wrong window / process in focus as it always searches for some window called Focus Proxy. 
With Firefox it's the same. Though sometime the wrong tab title is returned 

Happy Easter by the way

**Comment by mstarke** [comment] 2017-09-14 07:09
There have been more fixes to the Autotype system regarding wrong windows titles (focus proxies, and the lot) that should make the system more robust and usable. Could any of you try the continuous build to see if this fixes the reported issues?

**Comment by lifepillar** [comment] 2017-09-20 07:56
I have just built the current master from source. Global autotype appears to work as expected. A couple of remarks:

- checking *Enable global Autotype* in the preferences does not immediately enable global autotype: I had to quit and re-open MacPass to have it working;
-  matching (in browsers) uses only the title of the web page (as it appears in the `<title>` tag), even if other options are checked in MacPass's preferences (I think this is mentioned somewhere else in this thread). For other apps, it uses the app's name.

I have tested it with Safari, Firefox, and the App Store app.

**Comment by mstarke** [comment] 2017-09-20 08:16
Thanks for the feedback. You should be able to use the continuous build as it represent the current master, so no need for a custom build.

* There were a couple of hiccups with the hotkey registration. I have to check and see if I can iron out the one you reported as well.
* Autotype is a generalises approach for matching entries based on window titles. This way you get App names, Document names or URLs or titles for websites since the browser most of the time sets the window title to the html title attribute. What you refer to in the settings is a misunderstanding and I just updated the labels for the settings. Those settings have no effect on what is used from a browser window. MacPass only sees window titles, nothing more. Those setting refer to the field of an entry. Normally only the title attribute is matched but it's adjustable via the settings for your needs. The system gets more flexible if you also include window associations, as those allow you to add custom criteria for special cases and support wildcards and regular expression matching. If you want to get into the details of the autotype matching system, you should take a look at the documentation for [KeePass](http://keepass.info/help/base/autotype.html#autoglobal).

If you got any questions, just shoot.

**Comment by mstarke** [comment] 2017-09-20 08:20
I just checked for you first observation and am unable to see this. My steps:

* Disabled Autotype
* Quit MacPass
* Started MacPass
* Enabled Autotype
* Pressed Hotkey
* -> System worked.

Did you unlock the database? If the hot-key is pressed while no database is unlocked, MacPass should pop to the foreground and you have to unlock the database.

**Comment by lifepillar** [comment] 2017-09-20 13:02
>I just checked for you first observation and am unable to see this

You are right, I cannot reproduce it either.

>MacPass only sees window titles, nothing more. Those setting refer to the field of an entry.

Thanks for clarifying that. In fact, I had got it wrong.

**Comment by roland-d** [comment] 2017-11-21 22:15
Hey guys, a fresh Macpass users here. I don't have a problem anymore but something I encountered and wish to share with you. I had set my Autotype key sequence to ALT-SHIFT-A on my Mac and this never triggered the Autotype function. Switched the sequence to CTRL-SHIFT-A and things started working for me. Thank you for a great product.

Specs are:
MacBook Pro (Retina, 15-inch, Mid 2014)
MACOS 10.13.1
MacPass Version 0.7.1 (20171118111152-continuous)

**Comment by mstarke** [comment] 2017-11-27 06:24
Considering you issue: The default shortcut for autotype (not Global autotype) is Alt-Shift-A so this might clash.

**Comment by roland-d** [comment] 2017-11-27 10:05
@mstarke Ah thanks for that explanation. I am now used to the CTRL-SHIFT-A :)

**Comment by mstarke** [comment] 2017-12-11 16:09
I'm closing this since the actual issue seems to be fixed.

**Closed by mstarke** 2017-12-11 16:09 UTC
