### ISSUE TITLE
Entries in "Notes"-Field deleted after restart

### ISSUE THREAD

**Issue by dflick** [mstarke/MacPass#445] opened 2016-03-29 13:36 UTC
Hi,
in newest version, Version 0.6.2 (12420), the "Notes"-field is deleted after saving and restarting MacPass.
Does anyone else have this kind of error?
It's reproducible: I create an entry, add something to the notes-field, save DB, quit MacPass and start it again ... Notes-field empty ... 

Regards,
Daniel

**Comment by mstarke** [comment] 2016-03-29 14:42
I can reproduce the bug on groups not on entries and only by editing and then saving without leaving the notes field. If i exit the notes field the notes get saved (and loaded) correctly.

**Comment by dflick** [comment] 2016-03-29 18:57
I did the following:

1. new entry + notes, save, exit -> start again, new entry but no notes
2. edit this entry, add note, save, exit -> start again, check entry, no note
BUT 3. edit entry, add note, select another entry, save, exit -> start again, check entry, notes field is filled with my note

WTF? :D

**Comment by fusenigk** [comment] 2016-04-14 13:44
I can reproduce this bug too.

**Comment by EntropyWorks** [comment] 2016-05-05 20:01
I don't know if this is the same bug or different Notes issue.  I can no longer modify tor add Notes field in any of my entries. All my the previous Notes entries are readable but I can't modify them. Opening the Inspector and clicking the Edit button doesn't seem to do anything.

**Comment by tcz305** [comment] 2016-05-06 05:37
I have the same issue.

Notes are not always saved when I create a new note, save and quit. On app reopen the notes field is empty and I sometimes have to renter the note several times, save, and reopen for it to stick.

**Comment by ierdnah** [comment] 2016-05-17 21:54
I have the same issue. The new content added to “Notes” field from kdb databases it’s not saved from version 0.6.
In version 0.5.2 saving new added content in “notes” field works.

**Comment by mstarke** [comment] 2016-05-18 08:16
I switched to controller bindings and this seems to have added some "nice" features but was actually aimed to remove all the "changes aren't saved" bugs. Sorry for taking so long to fix this!

**Comment by ierdnah** [comment] 2016-05-18 08:45
With latest version build from git the Notes field is readonly.

**Comment by mstarke** [comment] 2016-05-18 08:48
The current master is a WIP for editing with History support so there are a couple of things broken…

**Comment by ierdnah** [comment] 2016-05-26 08:56
Which commit can be used for notes editing to work ?

**Comment by mstarke** [comment] 2016-10-17 16:52
Should be fixed with 2e1e4ad5acd2364825c19c38c81e56af58e9bbe3

**Closed by mstarke** 2016-10-17 16:52 UTC
Labels: Bug

**Comment by achalddave** [comment] 2017-03-01 18:22
Thank you for the quick fix! One note: It would be helpful if this were noted in the FAQs or even reported in the application itself, especially since the issue has been known and hasn't been fixed in a stable release for about a year. I have been losing notes for over a week and did not realize it until just now when I went back to look one up.
