### ISSUE TITLE
[Feature Request] Database sync

### ISSUE THREAD

**Issue by ElizarovEugene** [mstarke/MacPass#636] opened 2017-08-23 15:42 UTC
We use KeePass in our companies and one person has access to one database. Periodically, each of us can make changes to the database and synchronize with a single base, lying on a common ball, from where all, using synchronization, can also receive these changes. I would like to see the possibility of synchronizing the database in your application

**Comment by mstarke** [comment] 2017-08-23 15:45
Duplicate of #83. The current KeePassKit release supports this, the continous build has some functionality already working when the database file is changed outside of the application but it's all not implemented nor tested.

**Closed by mstarke** 2017-08-23 15:45 UTC
Labels: Duplicate
