### ISSUE TITLE
[Feature Request] Merge/compare save conflicts of password database

### ISSUE THREAD

**Issue by rfilmyer** [mstarke/MacPass#317] opened 2015-02-25 17:11 UTC
Not sure if this is possible cryptographically, but I'd like a way to resolve conflicts of a password database when saving- I have my database on Google Drive and accidentally made a change from another device without having MacPass save first, and I'd like a way to evaluate those changes.

**Comment by mstarke** [comment] 2015-02-26 11:33
That's the currently missing synch feature. It's on the todo list. But don't ask me when it's done ;).

**Comment by mstarke** [comment] 2015-02-26 11:36
Duplicate of #83

**Closed by mstarke** 2015-02-26 11:36 UTC
Labels: duplicate
