### ISSUE TITLE
Paste Password into MacPass

### ISSUE THREAD

**Issue by eweiss99** [mstarke/MacPass#372] opened 2015-09-04 13:44 UTC
On 0.4.1 and 0.5.1 you cannot save a password that you paste into MacPass.  Use case:  open an new account.  Open an editor and write the password.  Copy and paste the password into the web site (usually twice).  Now copy the password into MacPass.  It appears in MacPass, but when you save MacPass, the password is lost without any warning.

**Comment by DominusExult** [comment] 2015-09-06 10:03
Please elaborate with your exact steps in MacPass (what do you click and execute with shortcuts between opening and closing MacPass).
Is it a keepass 1.x ir 2.x database? Where in the database do you add the new entry? Etc...

Because I cannot reproduce this, so I assume the error is somewhere else in the procedure...

**Comment by mstarke** [comment] 2015-09-07 08:38
There is an often reported issue with input fields not saving their content on save, this has to do with not using object controllers for the binding. I did overlook this in the first implementation and have it on my list of things to improve in future releases.

**Comment by eweiss99** [comment] 2015-09-07 14:22
I tried duplicating the problem, and have not been able to.  I did shut down my Mac in between my problem and it working, so maybe that is part of the solution.  I am using a 2.x database.  I also am storing the database in DropBox so I can use it on iOS hardware.

**Comment by eweiss99** [comment] 2015-09-07 14:53
Do you have a work around for the problem?

**Comment by mstarke** [comment] 2015-09-17 08:55
If you move the focus away from input fields they should update the model.

**Comment by mstarke** [comment] 2015-12-27 20:41
This issue and many related to  editors not finishing their edit session before a save should be fixed with the move to object controllers in the current master. I have however not been able to get custom attribute and autotype editing to work the same way as there are more layers of controllers involved.

**Closed** 2015-12-27 20:41 UTC

**Comment by eweiss99** [comment] 2015-12-28 12:21
Thanks for the update and solution.

**Comment by eweiss99** [comment] 2015-12-28 12:21
Thanks for the update and solution.On Dec 27, 2015, at 3:41 PM, Michael Starke <notifications@github.com> wrote:Closed #372.—Reply to this email directly or view it on GitHub.
