### ISSUE TITLE
file corrupt when open db with keepass2

### ISSUE THREAD

**Issue by ilgio** [mstarke/MacPass#663] opened 2017-10-16 11:29 UTC
I tested the file created with macpass and opened with keepass2

I add element in macpass or keepass2 and it is ok in both
I insert an file attach with keepass2, it is ok in both
I insert an file attach with macpass, the file is corrupt when I open with keepass2, instead it is ok with macpass

**Comment by mstarke** [comment] 2017-10-16 14:18
What Version of macpass are you using, what settings do you use for the database-keyderivation?
I cannot reproduce this behaviour with the current continuous build neither with the old KDBX3.1 nor the newer KDBX4.0 file version.

**Comment by ilgio** [comment] 2017-10-16 16:47
![schermata 2017-10-16 alle 18 46 21](https://user-images.githubusercontent.com/26309528/31624273-70b0a280-b2a2-11e7-8616-01ecb9415898.png)
![schermata 2017-10-16 alle 18 45 58](https://user-images.githubusercontent.com/26309528/31624274-70dc7e64-b2a2-11e7-9985-bf5cd6465a57.png)

**Comment by mstarke** [comment] 2017-10-16 16:51
You're using an old continuous release (Build date is 2017/06/17) there were some fixes regarding attachment storage that should be resolved in the current continuous build.

**Comment by ilgio** [comment] 2017-10-18 08:34
thx

**Comment by mstarke** [comment] 2017-10-19 11:36
I think this is resolved then

**Closed by mstarke** 2017-10-19 11:36 UTC
Labels: Help Wanted!
