### ISSUE TITLE
macOS 10.13 drag and drop not working

### ISSUE THREAD

**Issue by cipnt** [mstarke/MacPass#654] opened 2017-10-02 18:41 UTC
After upgrading to High Sierra it seems I can no longer drag and drop entries from one group to another.
As soon as the cursor goes over the side bard it cancels the operation
[See screen recording](https://giphy.com/embed/l4Ep9iAmlOCOcMCJ2)

MacPass
Version 0.6.2 (12420)

macOS
10.13 (17A365)

**Comment by mstarke** [comment] 2017-10-02 19:23
Fixed in current continuous release. Duplicate of #639

**Closed by mstarke** 2017-10-02 19:23 UTC
