### ISSUE TITLE
Multiple Select

### ISSUE THREAD

**Issue by edm00se** [mstarke/MacPass#340] opened 2015-05-27 01:40 UTC
Feature request: multiple select, for assigning entries to categories, for instance.

**Comment by Nes-si** [comment] 2016-02-23 10:38
+1.
Also for deleting and other actions.
Please!

**Comment by mstarke** [comment] 2016-02-26 09:53
I've got multiselction for simple dragging/deleting/etc. working. Since multi-editing is a bit more work I'll might skip this in the first run!

**Comment by mstarke** [comment] 2016-02-26 09:56
Duplicate of #285

**Closed by mstarke** 2016-02-26 09:56 UTC
Labels: Duplicate
