### ISSUE TITLE
Setting an invalidation date closes opened database

### ISSUE THREAD

**Issue by suchkultur** [mstarke/MacPass#327] opened 2015-04-07 11:08 UTC
When i attach an invalidation date to an database entry using the date picker, the kdbx file is closed after pressing the button which sets the date. The invalidation date is set anyways, but i am a bit puzzled from this behaviour. Bug or (security) feature(?)

Version 0.5.1 (2556) (binary release from github), using kdbx files.

**Comment by mstarke** [comment] 2015-04-07 15:02
It's a bug not a feature. A known one too, fixed as well but not released as binary. Please take the time to search for closed issues before reporting a new on. I know it sounds a bit nit-picky but it makes me happy if you try :-)

Duplicate of #277

**Closed by mstarke** 2015-04-07 15:02 UTC
Labels: Duplicate

**Comment by suchkultur** [comment] 2015-04-07 15:15
Hi Michael,


sorry, i never reported a bug on github and did not know that the filters input field
allows free text searches. I will look closer next time before i open an issue again :-)




—
Gruß,
Stefan

**Comment by mstarke** [comment] 2015-04-07 15:25
Do not take it the wrong way. It's a line everyone that reports a duplicate get's. It's awesome that so many use MacPass. Never would have guessed that the tool would attract such an amount of users. And not only attract bot not scare them away right after that!
