### ISSUE TITLE
Can not open database

### ISSUE THREAD

**Issue by georgexsh** [mstarke/MacPass#329] opened 2015-04-15 07:59 UTC
env info:
MacPass 0.5.1 (2556)
OSX 10.10.3 (14D131)
database created by Keepass 1.x windows

steps:
open MacPass
select database file
input master password
click "unlock" (解锁)
then, nothing happens

**Comment by HomeSen** [comment] 2015-04-15 08:04
MacPass only supports KeePass 2 databases, if I'm not completely mistaken ;)

In order to use your existing database, you can install/download KeePass
2 on Windows, import the .kdb (KeePass 1.x database) and save it as
.kdbx (KeePass 2.x database)

Am 15.04.2015 um 10:00 schrieb georgexsh:

**Comment by mstarke** [comment] 2015-04-15 08:08
Nope. Macpass supports both formats. It's a bug. But it's quite hard to debug.

**Comment by HomeSen** [comment] 2015-04-15 08:10
Ah, okay, sorry. Didn't know that (mainly dueto me never having used
version 1.x). Maybe I should have RTFM'd before replying :$

Am 15.04.2015 um 10:08 schrieb Michael Starke:

**Comment by mstarke** [comment] 2015-04-15 08:34
@georgexsh I know it's a sensitive Information but my only guess right now is you're using Chinese characters as a password, I'll try to reproduce the error on my side and if successful try to fix the issue.

**Comment by georgexsh** [comment] 2015-04-15 09:30
@mstarke unfortunately, my password do no contains special character but regular ascii chars. 
is there any more information I could provide?
and, thanks for your kind reply

**Comment by mstarke** [comment] 2015-04-18 13:17
@georgexsh can you take a look at the system log to see if any assertion prevents MacPass from proceeding? You report that nothing happens - not even an error message - suggest a low-level error.

**Comment by georgexsh** [comment] 2015-04-18 18:26
@mstarke log goes :
```
15/4/19 02:23:51.502 MacPass[3511]: Unsupported algorithm
```
part of the following backtrace:
```
15/4/19 02:23:51.552 MacPass[3511]: (
	0   CoreFoundation                      0x00007fff91e8403c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x00007fff87bde76e objc_exception_throw + 43
	2   MacPass                             0x00000001045adfb2 MacPass + 626610
	3   MacPass                             0x00000001045adc01 MacPass + 625665
	4   MacPass                             0x00000001045ae10e MacPass + 626958
	5   MacPass                             0x000000010459ab52 MacPass + 547666
	6   MacPass                             0x000000010459a7f1 MacPass + 546801
	7   MacPass                             0x000000010453e8fc MacPass + 170236
	8   MacPass                             0x000000010452778b MacPass + 75659
	9   libsystem_trace.dylib               0x00007fff8cbf1cd7 _os_activity_initiate + 75
...
```

**Comment by georgexsh** [comment] 2015-04-18 18:30
@mstarke yeah, I changed database encrypt algorithm from twofish to aes using keepass, and now macpass could open it!

**Comment by mstarke** [comment] 2015-04-18 18:33
Nice one! I should try to catch that error a bit better and present the UI for it!

**Comment by ajsgithub** [comment] 2015-04-18 18:44
I'm also having trouble opening my database, but I see something different in the logs:

Apr 18 12:35:38 Zucchi.local MacPass[562]: Failed to connect (allowAllFilesCheckButton) outlet from (MPDocumentController) to (NSButton): missing setter or instance variable
Apr 18 12:35:38 Zucchi MacPass[562]: assertion failed: 14D136: libxpc.dylib + 62495 [D35D0DB2-D7BD-3BE4-8378-062BFE545E1D]: 0x89

**Comment by ajsgithub** [comment] 2015-04-18 18:45
This started after I updated to the latest OS X Yosemite.

**Comment by ajsgithub** [comment] 2015-04-19 03:06
Restored from TimeMachine and it's working again.  Never mind.

**Comment by mstarke** [comment] 2015-04-21 13:12
The error from the outlet is a bug that was introduced when I converted .xib files. Must have missed this one since there were several in other files which I did fix. But it's for the accessory view in the open dialog and has no impact on the decryption problem.

It would be nice though why your restored file works and what was broken in the other one. Did you make any changes? If so, there might still be a bug lingering around that caused this behaviour.

**Comment by ajsgithub** [comment] 2015-04-21 17:05
The only change that I recall was adding a few new entries.

I was in a bit of a panic as I had a submission deadline and so I wasn't as meticulous as I should have been while troubleshooting.  I think, though, that the file may have gotten corrupted during syncing between one of several computers that I use.  Just a guess at this point.

**Comment by georgexsh** [comment] 2015-04-22 09:34
@ajsgithub would you mind open another issue then I could close this one

**Comment by ajsgithub** [comment] 2015-04-28 23:11
Go ahead a close this issue.  If I can recreate my problem, I'll open a new issue.

**Closed** 2015-04-29 05:48 UTC
Labels: Bug

**Comment by HomeSen** [comment] 2015-09-26 11:26
Hello!

 

New message, please read <http://banrangsit.com/spirits.php?p>

 

Patrick Walker

**Comment by HomeSen** [comment] 2015-10-12 14:01
Hello!

 

Important message, please read <http://za.jobdiagnosis.com/miles.php?b5>

 

Patrick Walker
