### ISSUE TITLE
Notes not being saved

### ISSUE THREAD

**Issue by celtea** [mstarke/MacPass#539] opened 2017-01-17 13:04 UTC
Having issues when I type text into the Notes box.  Even though I click "Save" or CTRL-S, when I close the database and reopen, the text was not saved.  Occassionally have had success in getting the text to save if I modify the password or another field.

**Comment by mstarke** [comment] 2017-01-17 13:17
This is a well known and often reported problem, that is fixed in the current master. The next binary release will include the fix.

Duplicate of #478 #485 #487

**Closed by mstarke** 2017-01-17 13:17 UTC
Labels: Duplicate
