### ISSUE TITLE
Focus on database Root on db open

### ISSUE THREAD

**Issue by jeffmcneill** [mstarke/MacPass#443] opened 2016-03-28 02:39 UTC
Hello,

When the database opens, no part of the database is in focus. If I have to add an entry, then I need to click on Root (or some subfolder) first. However, there should be some default focus (Root is preferable). That way I can simply click the ADD and it sames time (and provides expected default focus).

**Comment by Ringelnatz** [comment] 2016-05-22 08:20
I would prefer that the default focus is on the folder that was open when the files was saved. This is IMHO the default behaviour of the official Windows application.

**Comment by mstarke** [comment] 2016-05-24 09:19
The feature @Ringelnatz describes is implemented in the master branch and will be included in the next release

**Closed by mstarke** 2016-05-24 09:19 UTC

**Comment by mstarke** [comment] 2016-05-24 09:27
duplicate of #424
