### ISSUE TITLE
OSX KeePass

### ISSUE THREAD

**Issue by replay111** [mstarke/MacPass#479] opened 2016-07-07 14:19 UTC
Have You seen this:

https://itunes.apple.com/pl/app/keepass-desktop/id1059196126?l=pl&mt=12

I Looks like Your tool....

**Comment by mstarke** [comment] 2016-07-07 14:20
Duplicate #400

**Comment by mstarke** [comment] 2016-07-07 14:20
Duplicate of #400

**Closed by mstarke** 2016-07-07 14:20 UTC
Labels: Duplicate
