### ISSUE TITLE
Direct input of length in password generator

### ISSUE THREAD

**Issue by timbru31** [mstarke/MacPass#415] opened 2016-01-28 13:01 UTC
Currently the password generator does show a text field where the length of the generated password is displayed, but it can't be adjusted by editing this text field, only via the slider.

It would be nice to make this text field not readonly, it's sometimes easier to input the number directly if you have to follow different password policies.

Cheers,
Tim

**Comment by mariosangiorgio** [comment] 2016-02-22 23:43
+1 I might give it a try and implement it

**Comment by eouw0o83hf** [comment] 2016-05-21 23:54
+1 just ran into this issue today, would love to have that field be editable

**Comment by mariosangiorgio** [comment] 2016-05-22 08:04
The feature is in the pull request I sent.
@msrarke, is there any issue with it or are you going to accept and include it in the next release?

**Comment by mstarke** [comment] 2016-05-23 08:25
@mariosangiorgio merged!

**Closed by mstarke** 2016-05-23 08:25 UTC

**Comment by mstarke** [comment] 2019-01-30 09:51
It's working. The textfield just looks greyed out since it's rendered inside a popover. I just confirmed that you can click on it and enter a manual value.

**Comment by michaelfresco** [comment] 2019-01-30 13:22
@mstarke actually, you are right it's working. I always think it's broken because it does not immediately update when you start typing. Say you need a password with a length of 20, ideally, (in my opinion), it should read the inputs of "2 <pause> 0". So first give you password of length 2, then 20, while updating all the way. 

At the moment, it only updates when you press `<enter>`.
