### ISSUE TITLE
Cancelling expiration dialog locks database

### ISSUE THREAD

**Issue by nicdumz** [mstarke/MacPass#367] opened 2015-08-17 19:35 UTC
Version 0.5.1 (2556)

* Select an entry
* Click the gear next to expiration settings
* Click Cancel
-> Database is now locked

This is a bit surprising :smile: . I would expect cancel to just close the dialog.

Generally speaking, "Use preset" is greyed out / impossible to use, but fixing the "lock me out" part seems more important.

Thanks!

**Comment by mstarke** [comment] 2015-08-17 20:49
Duplicate of #277.

**Comment by mstarke** [comment] 2015-08-17 20:49
That reminds me. I wanted to release a binary ;)

**Closed by mstarke** 2015-08-17 20:49 UTC
Labels: Duplicate
