### ISSUE TITLE
cannot bootstrap Carthage

### ISSUE THREAD

**Issue by FerretDave** [mstarke/MacPass#447] opened 2016-04-04 11:17 UTC
Greetings, Attempting a first time build:
Following the instructions in the readme https://github.com/mstarke/MacPass/blob/master/README.md, I've installed brew and carthage, but am stuck at the bootstrap process:

>carthage bootstrap --platform Mac
Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be completed. (NSURLErrorDomain error -1001.)" UserInfo=0x7fec61d1c4b0 {NSErrorFailingURLStringKey=https://api.github.com/repos/sparkle-project/Sparkle/releases/tags/1.14.0, NSUnderlyingError=0x7fec641046f0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=https://api.github.com/repos/sparkle-project/Sparkle/releases/tags/1.14.0}

Am I missing something, does 'Install all Dependencies' refer to this bootstrap command, or something else that I need to have done previously?

**Comment by mstarke** [comment] 2016-04-04 11:22
This looks like a failing network request.

**Comment by mstarke** [comment] 2016-04-04 11:27
Just checked. It's working for me so it might have been an hiccup on GitHub's end.

**Comment by FerretDave** [comment] 2016-04-04 12:01
it happens every time for me, and if I try and view the URL myself, I get a
'not found'  for your repo, but it works ok for Sparkle !

and worth noting, that the error varies between a few different URLs each
time I run it:

Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be
completed. (NSURLErrorDomain error -1001.)" UserInfo=0x7fc18343b5d0
{NSErrorFailingURLStringKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1,
NSUnderlyingError=0x7fc183635760 "The operation couldn’t be completed.
(kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1}

Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be
completed. (NSURLErrorDomain error -1001.)" UserInfo=0x7fc18343b5d0
{NSErrorFailingURLStringKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1,
NSUnderlyingError=0x7fc183635760 "The operation couldn’t be completed.
(kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1}

Error Domain=NSURLErrorDomain Code=-1001 "The operation couldn’t be
completed. (NSURLErrorDomain error -1001.)" UserInfo=0x7f9a12f06300
{NSErrorFailingURLStringKey=
https://api.github.com/repos/sparkle-project/Sparkle/releases/tags/1.14.0,
NSUnderlyingError=0x7f9a12c5fe50 "The operation couldn’t be completed.
(kCFErrorDomainCFNetwork error -1001.)", NSErrorFailingURLKey=
https://api.github.com/repos/sparkle-project/Sparkle/releases/tags/1.14.0}

Error Domain=NSURLErrorDomain Code=-1005 "The operation couldn’t be
completed. (NSURLErrorDomain error -1005.)" UserInfo=0x7ff062d0b3b0
{NSErrorFailingURLStringKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1,
NSErrorFailingURLKey=
https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1,
_kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57,
NSUnderlyingError=0x7ff062d0fa20 "The operation couldn’t be completed.
(kCFErrorDomainCFNetwork error -1005.)"}

>curl
https://api.github.com/repos/mstarke/KeePassKit/releases/tags/4406caed2050c0b5be911d66589647c205660f32
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

>curl https://api.github.com/repos/mstarke/HNHUi/releases/tags/1.0.1
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}


curl
https://api.github.com/repos/sparkle-project/Sparkle/releases/tags/1.14.0
|head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time
 Current
                                 Dload  Upload   Total   Spent    Left
 Speed
100  4963  100  4963    0     0   8799      0 --:--:-- --:--:-- --:--:--
 8799
{
  "url": "
https://api.github.com/repos/sparkle-project/Sparkle/releases/2791202",
  "assets_url": "
https://api.github.com/repos/sparkle-project/Sparkle/releases/2791202/assets
",
  "upload_url": "
https://uploads.github.com/repos/sparkle-project/Sparkle/releases/2791202/assets{?name,label}
",
  "html_url": "
https://github.com/sparkle-project/Sparkle/releases/tag/1.14.0",
  "id": 2791202,
  "tag_name": "1.14.0",
  "target_commitish": "master",
  "name": "",
  "draft": false,

**Comment by mstarke** [comment] 2016-04-04 12:15
I have no clue why the api doesn't work, I did not change anything at my end. The tag is there. I just tested with Carthage 0.15.2 and it works as well. Fetches everything without an issue.

**Comment by FerretDave** [comment] 2016-04-04 13:10
Carthage 0.15.2 is the one I'm using, I'll try wiping out the install and
reinstalling brew/carthage from scratch, to see if that makes any
difference.

**Comment by FerretDave** [comment] 2016-04-05 08:23
Well, removing the MacPass dir, and carthage completely, and starting again, made no difference. that carthage bootstrap just doesn't seem to like my system (running on Yosemite). I've obviously got *some* connectivity as I can clone from github ok, just cannot boostrap with carthage. Is there a way to manually do what carthage does?

I will give up trying to compile for now, how long till a new binary is released?

>git clone https://github.com/mstarke/MacPass
Cloning into 'MacPass'...
remote: Counting objects: 9884, done.
remote: Total 9884 (delta 0), reused 0 (delta 0), pack-reused 9884
Receiving objects: 100% (9884/9884), 21.77 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (6510/6510), done.
Checking connectivity... done.
Checking out files: 100% (663/663), done.
>cd MacPass

>git submodule update --init --recursive
Submodule 'DDHotKey' (https://github.com/mstarke/DDHotKey.git) registered for path 'DDHotKey'
Submodule 'TransformerKit' (https://github.com/mattt/TransformerKit.git) registered for path 'TransformerKit'
Cloning into 'DDHotKey'...
remote: Counting objects: 114, done.
remote: Total 114 (delta 0), reused 0 (delta 0), pack-reused 114
Receiving objects: 100% (114/114), 64.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (61/61), done.
Checking connectivity... done.
Submodule path 'DDHotKey': checked out 'dfab50eb22782850ec836a92d56d16bdb6b5912a'
Cloning into 'TransformerKit'...
remote: Counting objects: 417, done.
remote: Total 417 (delta 0), reused 0 (delta 0), pack-reused 417
Receiving objects: 100% (417/417), 80.68 KiB | 0 bytes/s, done.
Resolving deltas: 100% (238/238), done.
Checking connectivity... done.
Submodule path 'TransformerKit': checked out '337c309a4cf49ddec8902fd6de6d08b2cf8bd95f'

>carthage bootstrap --platform Mac
Error Domain=NSURLErrorDomain Code=-1005 "The operation couldn’t be completed. (NSURLErrorDomain error -1005.)" UserInfo=0x7fcb21f15350 {NSErrorFailingURLStringKey=https://api.github.com/repos/mstarke/KeePassKit/releases/tags/4406caed2050c0b5be911d66589647c205660f32, NSErrorFailingURLKey=https://api.github.com/repos/mstarke/KeePassKit/releases/tags/4406caed2050c0b5be911d66589647c205660f32, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=57, NSUnderlyingError=0x7fcb21f154f0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1005.)"}

>curl https://api.github.com/repos/mstarke/KeePassKit/releases/tags/4406caed2050c0b5be911d66589647c205660f32
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}

**Comment by mstarke** [comment] 2016-04-06 09:31
I'll try to reproduce this using a VM.

**Comment by mstarke** [comment] 2016-04-12 07:20
Since this is now happening to more than one person I'm concerned :(

**Comment by mstarke** [comment] 2016-04-12 07:28
I'm suspecting this has something to do with the github access token.

Is this possibly related?
http://stackoverflow.com/questions/35790585/carthage-update-error-github-api-request-failed-bad-credentials/

https://github.com/Carthage/Carthage/issues/1188#issuecomment-195918921

**Comment by FerretDave** [comment] 2016-04-12 08:36
Just tried the .gitconfig changes noted in that carthage reference - that didn't make any difference I'm afraid, though I was never prompted for a password when I tried the git clone - then again, I'm not getting any bad credentials error anyway.

**Comment by FerretDave** [comment] 2016-04-12 08:37
How about just pushing a binary out of the latest code ? ;-)

**Comment by mstarke** [comment] 2016-04-12 08:52
I only try to publish binary of code that is actually working properly. Master currently is in a in-between state and since I had no time to put work into MacPass I consider it not worth it.

**Comment by mstarke** [comment] 2016-04-12 08:53
And again, I have no clue why the bootsrap process fails as it works on all my setups.

**Comment by mstarke** [comment] 2016-08-17 08:47
I'm closing this in the hope that this was a local issue

**Closed by mstarke** 2016-08-17 08:47 UTC
Labels: Deployment
