### ISSUE TITLE
delete seems to delete all entries within a group

### ISSUE THREAD

**Issue by gghose** [mstarke/MacPass#581] opened 2017-05-05 18:15 UTC
When I hit the delete key it applies to all entries, not just the selected one.

**Comment by mstarke** [comment] 2017-05-05 20:44
The delete key is not associated with delte but `⌘+←`. Did you remapt the keys?
What Version of MacPass? Custom build or 0.6.2 binary release? I am unable to reproduce this behavoir with the current HEAD of develep

**Comment by gghose** [comment] 2017-05-05 21:16
This is really weird..... Now I can't replicate the bug......... I have no
explanation. It was the binary 0.6.2. release, by the way.

**Comment by mstarke** [comment] 2017-05-08 16:53
Since 0.6.2 is so old I close this until you can reproduce it. Then please reopen the issue!

**Closed by mstarke** 2017-05-08 16:53 UTC
Labels: Bug, Help Wanted!
