### ISSUE TITLE
Changes in one field not saved if focus not moved to another field first

### ISSUE THREAD

**Issue by G4nda1f** [mstarke/MacPass#537] opened 2017-01-12 00:55 UTC
First I'd like to say MacPass is definitely the best app on Mac that I've seen which works with KeePass databases.  However, I've recently noticed an issue that exihibits behavior as follows:

1. Make a change in one field of an existing MacPass record
1. The black dot appears in the red close button in upper left of the MacPass window
1. Save it with Cmd + S (don't move focus from the one field that was updated)
1. Close MacPass
1. Reopen MacPass
1. Find the record you updated in the first step and the changes are not there

At least this has been my experience.  I'm running macOS Sierra 10.12.2 with MacPass version 0.6.2.

Now if I tab out of the field I updated or change focus to another record (really just move off the field that was updated by whatever means you'd like) then it will save my updates, but if focus doesn't change to a different field, the updates are not saved.

Now, in this situation the system does appear to know a change has been made (indicated by the dot in the red exit button) but the record's "Modified" date is not updated until focus is moved out of the field that was modified.  So it seems like a cache of the field's information is not updated until you move off the field and thus the previous cached data is saved again, thereby **not** incorporating the latest changes.

**Comment by mstarke** [comment] 2017-01-12 10:28
This is a well known and often reported problem, that is fixed in the current master. The next binary release will include the fix.

Duplicate of #478 #485 #487

**Closed by mstarke** 2017-01-12 10:28 UTC

**Comment by bz007** [comment] 2017-01-12 11:06
Please make new binary because this well known issue is really critical and causes passwords may be lost.

**Comment by G4nda1f** [comment] 2017-01-12 15:52
My apologies for the duplicate.  Before submitting, I did a search (apparently among the open cases) and didn't see anything that seemed like this issue.

**Comment by mstarke** [comment] 2017-01-12 15:54
@G4nda1f no worries :)
@bz007 I'll do my best to get 0.7 released soon.
