### ISSUE TITLE
Multiple databases badly handled by KeePassHttp

### ISSUE THREAD

**Issue by woyczek** [mstarke/MacPass#517] opened 2016-11-29 07:35 UTC
While multiple databases are openend, Macpass is unable to handled it correctly.

The one used by KeePassHTTP is the first opened. It should be the active, or the one selected in an option.

It even could be both, as with the windows port of keepass.

**Comment by mstarke** [comment] 2016-11-29 09:11
Duplicate of https://github.com/MacPass/MacPassHTTP/issues/8

**Closed by mstarke** 2016-11-29 09:11 UTC
Labels: Duplicate
